@Api_HostAddress = http://localhost:5097

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json


###
# @name login
POST  http://localhost:5097/api/auth/login
Content-Type: application/json

{
    "UserName" : "ruslan",
    "password" : "123456"
}

### parking ticket info shymkent
@token = {{login.response.body.access_token}}
GET http://localhost:5097/api/v1/documents/037AE880-B0B9-44F1-A955-94183C803638/approve
Content-Type: application/json
Authorization: Bearer {{token}}